
SET SQL DIALECT 3; 

/* CREATE DATABASE 'd:\Develop\Database\istari.gdb' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8; */


/* Domain definitions */
CREATE DOMAIN MY_BOOL AS SMALLINT
         DEFAULT 1 NOT NULL;
COMMIT WORK;

/* Table: PARAMETERS, Owner: SYSDBA */
CREATE TABLE PARAMETERS (PARAM_NAME VARCHAR(50) NOT NULL,
        PARAM_VALUE VARCHAR(100),
CONSTRAINT PK_PARAMETERS PRIMARY KEY (PARAM_NAME));

/* Domain constraints */
ALTER DOMAIN MY_BOOL ADD CONSTRAINT
         CHECK (VALUE IN (0,1));
