
SET SQL DIALECT 3; 

/* CREATE DATABASE 'd:\Develop\Database\istari.gdb' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8; */


/*  Generators or sequences */
CREATE GENERATOR GEN_USERS_ID;

/* Domain definitions */
CREATE DOMAIN MY_BOOL AS SMALLINT
         DEFAULT 1 NOT NULL;
CREATE DOMAIN USERROLE AS SMALLINT
         DEFAULT 2 NOT NULL;
COMMIT WORK;

/* Table: PARAMETERS, Owner: SYSDBA */
CREATE TABLE PARAMETERS (PARAM_NAME VARCHAR(50) NOT NULL,
        PARAM_VALUE VARCHAR(100),
CONSTRAINT PK_PARAMETERS PRIMARY KEY (PARAM_NAME));

/* Table: USERS, Owner: SYSDBA */
CREATE TABLE USERS (USER_ID SMALLINT NOT NULL,
        USER_LOGIN VARCHAR(50) NOT NULL,
        USER_FIO VARCHAR(70),
        USER_ROLE USERROLE,
        ISACTIVE MY_BOOL,
CONSTRAINT PK_USERS PRIMARY KEY (USER_ID));

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures headers */
CREATE OR ALTER PROCEDURE GET_USERID (USER_LOGIN VARCHAR(50) CHARACTER SET UTF8 NOT NULL)
RETURNS (USER_ID SMALLINT NOT NULL)
AS 
BEGIN EXIT; END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures bodies */

ALTER PROCEDURE GET_USERID (USER_LOGIN VARCHAR(50) CHARACTER SET UTF8 NOT NULL)
RETURNS (USER_ID SMALLINT NOT NULL)
AS 
begin
 IF(EXISTS(SELECT u.user_id FROM USERS u WHERE u.user_login = :user_login))
    THEN
        BEGIN 
           SELECT u.user_id FROM users u WHERE u.user_login = :user_login
           INTO :user_id;
        END
    ELSE
        BEGIN
            :user_id = GEN_ID(gen_users_id,1);
            INSERT INTO users (user_id, user_login) VALUES (:user_id, :user_login);
        END
end ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

/* Domain constraints */
ALTER DOMAIN MY_BOOL ADD CONSTRAINT
         CHECK (VALUE IN (0,1));
ALTER DOMAIN USERROLE ADD CONSTRAINT
         CHECK (VALUE IN (0, 1, 2));

/* Grant permissions for this database */
GRANT INSERT, SELECT ON USERS TO PROCEDURE GET_USERID;
GRANT USAGE ON SEQUENCE GEN_USERS_ID TO PROCEDURE GET_USERID;

/* Comments for database objects. */
COMMENT ON DOMAIN       USERROLE IS '0 - Admin, 1 - Manager, 2 - User';
